/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visual;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import javafx.application.Platform;
import javafx.scene.media.Media;

/**
 * La clase MusicM representa la interfaz gráfica para el reproductor de música.
 * Permite al usuario reproducir, pausar y detener canciones descargadas.
 * Extiende javax.swing.JFrame.
 *
 * @see javax.swing.JFrame
 */
public class MusicM extends javax.swing.JFrame {

    private javafx.scene.media.MediaPlayer mediaPlayer;

    /**
     * Constructor de la clase MusicM. Inicializa los componentes, configura el
     * reproductor de medios y añade un listener para el evento de cierre de la
     * ventana.
     *
     * @param SongName Nombre de la canción a reproducir.
     */
    public MusicM(String SongName) {
        initComponents();
        setupComponents(SongName);
        initializeMediaPlayer("download/" + SongName);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                // Aquí puedes manejar el evento de cierre de la ventana
                // Por ejemplo, puedes minimizar la ventana o simplemente ocultarla
                stopSong();
                dispose(); // Oculta la ventana en lugar de cerrarla

            }
        });
    }

    private void playSong() {
        if (mediaPlayer != null) {
            Platform.runLater(() -> mediaPlayer.play());
        }
    }

    // Método para pausar la reproducción de la canción
    private void pauseSong() {
        if (mediaPlayer != null) {
            Platform.runLater(() -> mediaPlayer.pause());
        }
    }

    /**
     * Configura los componentes de la interfaz con el nombre de la canción
     * seleccionada.
     *
     * @param selectedSong Nombre de la canción seleccionada.
     */
    private void setupComponents(String selectedSong) {
        jLabel1.setText(selectedSong);
    }

    /**
     * Inicializa el reproductor de medios con la ruta del archivo de la
     * canción. Utiliza Platform.runLater para ejecutar la inicialización en el
     * hilo de JavaFX.
     *
     * @param songFilePath Ruta del archivo de la canción.
     */
    private void initializeMediaPlayer(String songFilePath) {

        // JavaFX ya está inicializado, procede con la creación del reproductor
        Platform.runLater(() -> {
            Media media = new Media(new File(songFilePath).toURI().toString());
            mediaPlayer = new javafx.scene.media.MediaPlayer(media);
        });
    }
//

    private void stopSong() {
        if (mediaPlayer != null) {
            Platform.runLater(() -> {
                mediaPlayer.stop();
                mediaPlayer.dispose();
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonPlay = new javax.swing.JButton();
        jButtonPau = new javax.swing.JButton();
        button1 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Canción escogida");

        jButtonPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visual/play.jpg"))); // NOI18N
        jButtonPlay.setText("Play");
        jButtonPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayActionPerformed(evt);
            }
        });

        jButtonPau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visual/cafe.jpg"))); // NOI18N
        jButtonPau.setText("Pausa");
        jButtonPau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPauActionPerformed(evt);
            }
        });

        button1.setLabel("volver");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jButtonPlay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonPau)
                .addGap(71, 71, 71))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(369, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(68, 68, 68)
                        .addComponent(jButtonPau))
                    .addComponent(jButtonPlay))
                .addGap(43, 43, 43)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPauActionPerformed
        pauseSong();
    }//GEN-LAST:event_jButtonPauActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        /* Music regresar= new Music();
            regresar.setVisible(true);
            this.dispose();*/
    }//GEN-LAST:event_button1ActionPerformed

    private void jButtonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayActionPerformed
        playSong();
    }//GEN-LAST:event_jButtonPlayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.JButton jButtonPau;
    private javax.swing.JButton jButtonPlay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
