package Visual;

import java.io.File;
import java.io.IOException;
import javafx.scene.media.MediaPlayer;

/**
 * La clase VideoM representa una ventana que muestra un reproductor de video
 * para un archivo seleccionado. Extiende javax.swing.JFrame y utiliza el
 * reproductor de medios de Windows para reproducir el video.
 *
 * @autor Personal
 */
public class VideoM extends javax.swing.JFrame {

    private MediaPlayer mediaPlayer;
    private final String selectedVideo;

    /**
     * Crea una nueva instancia de VideoM para el video seleccionado.
     *
     * @param selectVido El nombre del video seleccionado.
     */
    public VideoM(String selectVido) {
        this.selectedVideo = selectVido;
        initComponents();

        setTitle("Reproduciendo " + selectedVideo);
        File file = new File("download/" + selectedVideo);

        if (file != null) {
            String relativePath = file.toURI().toString();
            String abosolutePath = relativePath.substring(6);
            System.out.println("direccion del archivo: " + abosolutePath);// Ruta relativa al archivo de video en tu proyecto

            playVideoWithWindowsMediaPlayer(abosolutePath);
        }

        setResizable(false);
        setLocationRelativeTo(null);
        this.setLocationRelativeTo(null);

        setupComponents(selectedVideo);

        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                stopVideo();
                dispose();
            }
        });
    }

    /**
     * Reproduce el video utilizando el reproductor de medios de Windows.
     *
     * @param videoFilePath La ruta del archivo de video a reproducir.
     */
    public static void playVideoWithWindowsMediaPlayer(String videoFilePath) {
        System.out.println(videoFilePath);
        try {
            File videoFile = new File(videoFilePath);
            if (!videoFile.exists()) {
                System.out.println("El archivo de video no existe: " 
                        + videoFilePath);
                return;
            }

            // Construir el comando para abrir el reproductor de video de Windows
            ProcessBuilder builder = new ProcessBuilder("cmd.exe", "/c",
                    "start", "wmplayer", videoFilePath);
            builder.start();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    /**
     * Configura los componentes de la interfaz gráfica con el nombre del video
     * seleccionado.
     *
     * @param selectedSong El nombre del video seleccionado.
     */
    private void setupComponents(String selectedSong) {
        Text.setText(selectedSong);
    }

    private void stopVideo() {
        if (mediaPlayer != null) {
            mediaPlayer.stop();
            mediaPlayer.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Text = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Text.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Text)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text;
    // End of variables declaration//GEN-END:variables
}
